name: Main workflow
on: 
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: npm install
      run: cd website && npm install

    - name: npm build
      run: cd website && npm build

    - name: Deploying to GitHub Pages
      command: |
        git config --global user.email "<GITHUB_USERNAME>@users.noreply.github.com"
        git config --global user.name "<YOUR_NAME>"
        echo "machine github.com login <GITHUB_USERNAME> password $GITHUB_TOKEN" > ~/.netrc
        cd website && GIT_USER=<GIT_USER> npm publish-gh-pages

# workflow "Build Docs" {
#   on = "push"
#   resolves = ["Deploy Docs"]
# }

# action "Filter Master" {
#   uses = "actions/bin/filter@master"
#   args = "branch master"
# }

# action "Install" {
#   needs = ["Filter branch"]
#   uses = "actions/npm@master"
#   args = "install --prefix ./website"
# }

# action "Update version" {
#   needs = ["Install"]
#   uses = "clay/docusaurus-github-action@master"
#   args = "version"
# }

# action "Deploy Docs" {
#   needs = ["Update version"]
#   uses = "clay/docusaurus-github-action@master"
#   args="deploy"
#   secrets = ["DEPLOY_SSH_KEY"]
#   env={
#       BUILD_DIR = "website",
#       PROJECT_NAME = "site"
#   }
# }