name: Main workflow
on: 
  push:
    branches:
      - master
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@master
      with:
        version: '16'

    - name: yarn install
      run: cd website && yarn install
    - name: yarn build
      run: cd website && yarn build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Build output to publish to the `gh-pages` branch:
        publish_dir: ./website/build


# workflow "Build Docs" {
#   on = "push"
#   resolves = ["Deploy Docs"]
# }

# action "Filter Master" {
#   uses = "actions/bin/filter@master"
#   args = "branch master"
# }

# action "Install" {
#   needs = ["Filter branch"]
#   uses = "actions/yarn@master"
#   args = "install --prefix ./website"
# }

# action "Update version" {
#   needs = ["Install"]
#   uses = "clay/docusaurus-github-action@master"
#   args = "version"
# }

# action "Deploy Docs" {
#   needs = ["Update version"]
#   uses = "clay/docusaurus-github-action@master"
#   args="deploy"
#   secrets = ["DEPLOY_SSH_KEY"]
#   env={
#       BUILD_DIR = "website",
#       PROJECT_NAME = "site"
#   }
# }